spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/food
    username: postgres
    password: gbhfns
    driverClassName: org.postgresql.Driver
  data:
    redis:
      host: localhost
      port: 6379

  mail:
    password: ${mail.password}
    username: ${mail.username}
    host: ${mail.host}
    port: ${mail.port}
    protocol: smtp

authentication:
  jwt:
    secret: AbdaasdasdasdasfasgasASFASF
    expiration: 1h
  refresh:
    expiration: 1d

mail:
  username: username
  password: password
  host: host
  port: 123