spring:
  liquibase:
    enabled: true
    change-log: db/changelog/main-changelog.xml
  servlet:
    multipart:
      max-file-size: 2MB
      max-request-size: 2MB
      enabled: true
  datasource:
    url: jdbc:postgresql://localhost:5432/food
    username: postgres
    password: gbhfns
    driverClassName: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
  data:
    redis:
      host: localhost
      port: 6379

  mail:
    password: ${mail.password:stub}
    username: ${mail.username:stub}
    host: ${mail.host:stub}
    port: ${mail.port:stub}
    protocol: smtp

authentication:
  jwt:
    secret: c2VjcmV0S2V5MTIzNDU2Nzg5MDEyMzQ1Njc4OQBASDASFavsafasfasvbascascasvas
    expiration: 1h
  refresh:
    expiration: 1d

mail:
  enabled: false
  username: username
  password: password
  host: host
  port: 123
  url-to-where: http://localhost:8080

minio:
  access-key: minioadmin
  secret-key: minioadmin
  endpoint: http://localhost:9000
  bucket-name: image
  available-extensions:
    - png
    - jpg

management:
  endpoints:
    web:
      exposure:
        include: health,prometheus